name: component-ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  component:
    uses: ovx-labs/ci/.github/workflows/reusable-component-ci.yml@main
    with:
      component: genai-java-api
